name: "Arylation"
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Arylation"
  }
  inputs {
    key: "inputs-3856e4"
    value {
      components {
        identifiers {
          type: SMILES
          value: "F/C(F)=C\\C1=CC=C(C2=CC=CC=C2)C=C1"
        }
        amount {
          moles {
            value: 0.5
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "IC1=CC=CC=C1"
        }
        amount {
          moles {
            value: 1.5
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: NAME
          value: "THF"
        }
        amount {
          moles {
            value: 2.0
            units: MILLIMOLE
          }
        }
        reaction_role: SOLVENT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: BALL_MILL
      frequency {
        value: 600.0
        units: RPM
      }
      duration {
        value: 1.0
        units: SECOND
      }
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "F/C(C1=CC=CC=C1)=C/C2=CC=C(C3=CC=CC=C3)C=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 48.6
        }
      }
      reaction_role: PRODUCT
    }
    products {
      identifiers {
        type: SMILES
        value: "F/C(C1=CC=CC=C1)=C\\C2=CC=C(C3=CC=CC=C3)C=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 11.4
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Division of Applied Chemistry, Faculty of Engineering, Hokkaido University"
    }
    city: "Hokkaido"
    doi: "10.1039/d4mr00135d"
    publication_url: "https://pubs.rsc.org/en/content/articlepdf/2025/mr/d4mr00135d"
    record_created {
      time {
        value: "2025-05-09 16:17:20.054781"
      }
      person {
        name: "peter"
        email: "peterchao1@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e8a59b51f90846bbaa21476ec2b10001"
}
dataset_id: "cmcc_dataset-e8a59b51f90846bbaa21476ec2b114da"
