reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Photo Mechanochemical"
  }
  inputs {
    key: "acenaphthylene"
    value {
      components {
        identifiers {
          type: SMILES
          value: "C12=CC=CC(C=C3)=C1C3=CC=C2"
        }
        amount {
          moles {
            value: 7.89
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
        is_limiting: true
      }
      addition_order: 1
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 5.7
        }
      }
    }
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 89.3
        }
      }
    }
  }
  provenance {
    experimenter {
      orcid: "0000-0003-0344-3029"
      organization: "Department of Chemistry, Hunter College"
    }
    city: "New York"
    doi: "10.1039/D2FD00122E"
    publication_url: "https://doi.org/10.1039/D2FD00122E"
    record_created {
      time {
        value: "8/22/2024, 10:53 AM"
      }
      person {
        name: "Tzu-Hsuan Chao"
        orcid: "0000-0002-1345-0938"
        organization: "TAMU"
        email: "peterchao1@tamu.edu"
      }
    }
  }
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Photo Mechanochemical"
  }
  inputs {
    key: "acenaphthylene"
    value {
      components {
        identifiers {
          type: SMILES
          value: "C12=CC=CC(C=C3)=C1C3=CC=C2"
        }
        amount {
          moles {
            value: 7.89
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
        is_limiting: true
      }
      addition_order: 1
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 6.96
        }
      }
    }
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 80.04
        }
      }
    }
  }
  provenance {
    experimenter {
      orcid: "0000-0003-0344-3029"
      organization: "Department of Chemistry, Hunter College"
    }
    city: "New York"
    doi: "10.1039/D2FD00122E"
    publication_url: "https://doi.org/10.1039/D2FD00122E"
    record_created {
      time {
        value: "8/22/2024, 10:53 AM"
      }
      person {
        name: "Tzu-Hsuan Chao"
        orcid: "0000-0002-1345-0938"
        organization: "TAMU"
        email: "peterchao1@tamu.edu"
      }
    }
  }
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Photo Mechanochemical"
  }
  inputs {
    key: "acenaphthylene"
    value {
      components {
        identifiers {
          type: SMILES
          value: "C12=CC=CC(C=C3)=C1C3=CC=C2"
        }
        amount {
          moles {
            value: 7.89
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
        is_limiting: true
      }
      addition_order: 1
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 45.5
        }
      }
    }
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 19.5
        }
      }
    }
  }
  provenance {
    experimenter {
      orcid: "0000-0003-0344-3029"
      organization: "Department of Chemistry, Hunter College"
    }
    city: "New York"
    doi: "10.1039/D2FD00122E"
    publication_url: "https://doi.org/10.1039/D2FD00122E"
    record_created {
      time {
        value: "8/22/2024, 10:53 AM"
      }
      person {
        name: "Tzu-Hsuan Chao"
        orcid: "0000-0002-1345-0938"
        organization: "TAMU"
        email: "peterchao1@tamu.edu"
      }
    }
  }
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Photo Mechanochemical"
  }
  inputs {
    key: "acenaphthylene"
    value {
      components {
        identifiers {
          type: SMILES
          value: "C12=CC=CC(C=C3)=C1C3=CC=C2"
        }
        amount {
          moles {
            value: 7.89
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
        is_limiting: true
      }
      addition_order: 1
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 45.54
        }
      }
    }
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 53.46
        }
      }
    }
  }
  provenance {
    experimenter {
      orcid: "0000-0003-0344-3029"
      organization: "Department of Chemistry, Hunter College"
    }
    city: "New York"
    doi: "10.1039/D2FD00122E"
    publication_url: "https://doi.org/10.1039/D2FD00122E"
    record_created {
      time {
        value: "8/22/2024, 10:53 AM"
      }
      person {
        name: "Tzu-Hsuan Chao"
        orcid: "0000-0002-1345-0938"
        organization: "TAMU"
        email: "peterchao1@tamu.edu"
      }
    }
  }
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Photo Mechanochemical"
  }
  inputs {
    key: "acenaphthylene"
    value {
      components {
        identifiers {
          type: SMILES
          value: "C12=CC=CC(C=C3)=C1C3=CC=C2"
        }
        amount {
          moles {
            value: 7.89
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
        is_limiting: true
      }
      addition_order: 1
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 49.0
        }
      }
    }
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 51.0
        }
      }
    }
  }
  provenance {
    experimenter {
      orcid: "0000-0003-0344-3029"
      organization: "Department of Chemistry, Hunter College"
    }
    city: "New York"
    doi: "10.1039/D2FD00122E"
    publication_url: "https://doi.org/10.1039/D2FD00122E"
    record_created {
      time {
        value: "8/22/2024, 10:53 AM"
      }
      person {
        name: "Tzu-Hsuan Chao"
        orcid: "0000-0002-1345-0938"
        organization: "TAMU"
        email: "peterchao1@tamu.edu"
      }
    }
  }
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Photo Mechanochemical"
  }
  inputs {
    key: "acenaphthylene"
    value {
      components {
        identifiers {
          type: SMILES
          value: "C12=CC=CC(C=C3)=C1C3=CC=C2"
        }
        amount {
          moles {
            value: 7.89
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
        is_limiting: true
      }
      addition_order: 1
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 31.0
        }
      }
    }
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 69.0
        }
      }
    }
  }
  provenance {
    experimenter {
      orcid: "0000-0003-0344-3029"
      organization: "Department of Chemistry, Hunter College"
    }
    city: "New York"
    doi: "10.1039/D2FD00122E"
    publication_url: "https://doi.org/10.1039/D2FD00122E"
    record_created {
      time {
        value: "8/22/2024, 10:53 AM"
      }
      person {
        name: "Tzu-Hsuan Chao"
        orcid: "0000-0002-1345-0938"
        organization: "TAMU"
        email: "peterchao1@tamu.edu"
      }
    }
  }
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Photo Mechanochemical"
  }
  inputs {
    key: "acenaphthylene"
    value {
      components {
        identifiers {
          type: SMILES
          value: "C12=CC=CC(C=C3)=C1C3=CC=C2"
        }
        amount {
          moles {
            value: 7.89
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
        is_limiting: true
      }
      addition_order: 1
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 59.0
        }
      }
    }
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 41.0
        }
      }
    }
  }
  provenance {
    experimenter {
      orcid: "0000-0003-0344-3029"
      organization: "Department of Chemistry, Hunter College"
    }
    city: "New York"
    doi: "10.1039/D2FD00122E"
    publication_url: "https://doi.org/10.1039/D2FD00122E"
    record_created {
      time {
        value: "8/22/2024, 10:53 AM"
      }
      person {
        name: "Tzu-Hsuan Chao"
        orcid: "0000-0002-1345-0938"
        organization: "TAMU"
        email: "peterchao1@tamu.edu"
      }
    }
  }
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Photo Mechanochemical"
  }
  inputs {
    key: "acenaphthylene"
    value {
      components {
        identifiers {
          type: SMILES
          value: "C12=CC=CC(C=C3)=C1C3=CC=C2"
        }
        amount {
          moles {
            value: 7.89
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
        is_limiting: true
      }
      addition_order: 1
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 84.0
        }
      }
    }
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 16.0
        }
      }
    }
  }
  provenance {
    experimenter {
      orcid: "0000-0003-0344-3029"
      organization: "Department of Chemistry, Hunter College"
    }
    city: "New York"
    doi: "10.1039/D2FD00122E"
    publication_url: "https://doi.org/10.1039/D2FD00122E"
    record_created {
      time {
        value: "8/22/2024, 10:53 AM"
      }
      person {
        name: "Tzu-Hsuan Chao"
        orcid: "0000-0002-1345-0938"
        organization: "TAMU"
        email: "peterchao1@tamu.edu"
      }
    }
  }
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Photo Mechanochemical"
  }
  inputs {
    key: "acenaphthylene"
    value {
      components {
        identifiers {
          type: SMILES
          value: "C12=CC=CC(C=C3)=C1C3=CC=C2"
        }
        amount {
          moles {
            value: 7.89
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
        is_limiting: true
      }
      addition_order: 1
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 52.0
        }
      }
    }
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 48.0
        }
      }
    }
  }
  provenance {
    experimenter {
      orcid: "0000-0003-0344-3029"
      organization: "Department of Chemistry, Hunter College"
    }
    city: "New York"
    doi: "10.1039/D2FD00122E"
    publication_url: "https://doi.org/10.1039/D2FD00122E"
    record_created {
      time {
        value: "8/22/2024, 10:53 AM"
      }
      person {
        name: "Tzu-Hsuan Chao"
        orcid: "0000-0002-1345-0938"
        organization: "TAMU"
        email: "peterchao1@tamu.edu"
      }
    }
  }
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Photo Mechanochemical"
  }
  inputs {
    key: "acenaphthylene"
    value {
      components {
        identifiers {
          type: SMILES
          value: "C12=CC=CC(C=C3)=C1C3=CC=C2"
        }
        amount {
          moles {
            value: 7.89
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
        is_limiting: true
      }
      addition_order: 1
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 39.0
        }
      }
    }
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 61.0
        }
      }
    }
  }
  provenance {
    experimenter {
      orcid: "0000-0003-0344-3029"
      organization: "Department of Chemistry, Hunter College"
    }
    city: "New York"
    doi: "10.1039/D2FD00122E"
    publication_url: "https://doi.org/10.1039/D2FD00122E"
    record_created {
      time {
        value: "8/22/2024, 10:53 AM"
      }
      person {
        name: "Tzu-Hsuan Chao"
        orcid: "0000-0002-1345-0938"
        organization: "TAMU"
        email: "peterchao1@tamu.edu"
      }
    }
  }
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Photo Mechanochemical"
  }
  inputs {
    key: "acenaphthylene"
    value {
      components {
        identifiers {
          type: SMILES
          value: "C12=CC=CC(C=C3)=C1C3=CC=C2"
        }
        amount {
          moles {
            value: 7.89
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
        is_limiting: true
      }
      addition_order: 1
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 77.0
        }
      }
    }
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 23.0
        }
      }
    }
  }
  provenance {
    experimenter {
      orcid: "0000-0003-0344-3029"
      organization: "Department of Chemistry, Hunter College"
    }
    city: "New York"
    doi: "10.1039/D2FD00122E"
    publication_url: "https://doi.org/10.1039/D2FD00122E"
    record_created {
      time {
        value: "8/22/2024, 10:53 AM"
      }
      person {
        name: "Tzu-Hsuan Chao"
        orcid: "0000-0002-1345-0938"
        organization: "TAMU"
        email: "peterchao1@tamu.edu"
      }
    }
  }
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Photo Mechanochemical"
  }
  inputs {
    key: "acenaphthylene"
    value {
      components {
        identifiers {
          type: SMILES
          value: "C12=CC=CC(C=C3)=C1C3=CC=C2"
        }
        amount {
          moles {
            value: 7.89
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
        is_limiting: true
      }
      addition_order: 1
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 91.0
        }
      }
    }
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 9.0
        }
      }
    }
  }
  provenance {
    experimenter {
      orcid: "0000-0003-0344-3029"
      organization: "Department of Chemistry, Hunter College"
    }
    city: "New York"
    doi: "10.1039/D2FD00122E"
    publication_url: "https://doi.org/10.1039/D2FD00122E"
    record_created {
      time {
        value: "8/22/2024, 10:53 AM"
      }
      person {
        name: "Tzu-Hsuan Chao"
        orcid: "0000-0002-1345-0938"
        organization: "TAMU"
        email: "peterchao1@tamu.edu"
      }
    }
  }
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Photo Mechanochemical"
  }
  inputs {
    key: "acenaphthylene"
    value {
      components {
        identifiers {
          type: SMILES
          value: "C12=CC=CC(C=C3)=C1C3=CC=C2"
        }
        amount {
          moles {
            value: 7.89
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
        is_limiting: true
      }
      addition_order: 1
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 46.0
        }
      }
    }
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 54.0
        }
      }
    }
  }
  provenance {
    experimenter {
      orcid: "0000-0003-0344-3029"
      organization: "Department of Chemistry, Hunter College"
    }
    city: "New York"
    doi: "10.1039/D2FD00122E"
    publication_url: "https://doi.org/10.1039/D2FD00122E"
    record_created {
      time {
        value: "8/22/2024, 10:53 AM"
      }
      person {
        name: "Tzu-Hsuan Chao"
        orcid: "0000-0002-1345-0938"
        organization: "TAMU"
        email: "peterchao1@tamu.edu"
      }
    }
  }
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Photo Mechanochemical"
  }
  inputs {
    key: "acenaphthylene"
    value {
      components {
        identifiers {
          type: SMILES
          value: "C12=CC=CC(C=C3)=C1C3=CC=C2"
        }
        amount {
          moles {
            value: 7.89
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
        is_limiting: true
      }
      addition_order: 1
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 42.0
        }
      }
    }
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 58.0
        }
      }
    }
  }
  provenance {
    experimenter {
      orcid: "0000-0003-0344-3029"
      organization: "Department of Chemistry, Hunter College"
    }
    city: "New York"
    doi: "10.1039/D2FD00122E"
    publication_url: "https://doi.org/10.1039/D2FD00122E"
    record_created {
      time {
        value: "8/22/2024, 10:53 AM"
      }
      person {
        name: "Tzu-Hsuan Chao"
        orcid: "0000-0002-1345-0938"
        organization: "TAMU"
        email: "peterchao1@tamu.edu"
      }
    }
  }
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Photo Mechanochemical"
  }
  inputs {
    key: "acenaphthylene"
    value {
      components {
        identifiers {
          type: SMILES
          value: "C12=CC=CC(C=C3)=C1C3=CC=C2"
        }
        amount {
          moles {
            value: 7.89
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
        is_limiting: true
      }
      addition_order: 1
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 78.0
        }
      }
    }
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 22.0
        }
      }
    }
  }
  provenance {
    experimenter {
      orcid: "0000-0003-0344-3029"
      organization: "Department of Chemistry, Hunter College"
    }
    city: "New York"
    doi: "10.1039/D2FD00122E"
    publication_url: "https://doi.org/10.1039/D2FD00122E"
    record_created {
      time {
        value: "8/22/2024, 10:53 AM"
      }
      person {
        name: "Tzu-Hsuan Chao"
        orcid: "0000-0002-1345-0938"
        organization: "TAMU"
        email: "peterchao1@tamu.edu"
      }
    }
  }
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Photo Mechanochemical"
  }
  inputs {
    key: "acenaphthylene"
    value {
      components {
        identifiers {
          type: SMILES
          value: "C12=CC=CC(C=C3)=C1C3=CC=C2"
        }
        amount {
          moles {
            value: 7.89
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
        is_limiting: true
      }
      addition_order: 1
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 47.0
        }
      }
    }
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 53.0
        }
      }
    }
  }
  provenance {
    experimenter {
      orcid: "0000-0003-0344-3029"
      organization: "Department of Chemistry, Hunter College"
    }
    city: "New York"
    doi: "10.1039/D2FD00122E"
    publication_url: "https://doi.org/10.1039/D2FD00122E"
    record_created {
      time {
        value: "8/22/2024, 10:53 AM"
      }
      person {
        name: "Tzu-Hsuan Chao"
        orcid: "0000-0002-1345-0938"
        organization: "TAMU"
        email: "peterchao1@tamu.edu"
      }
    }
  }
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Photo Mechanochemical"
  }
  inputs {
    key: "acenaphthylene"
    value {
      components {
        identifiers {
          type: SMILES
          value: "C12=CC=CC(C=C3)=C1C3=CC=C2"
        }
        amount {
          moles {
            value: 7.89
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
        is_limiting: true
      }
      addition_order: 1
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 33.0
        }
      }
    }
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 67.0
        }
      }
    }
  }
  provenance {
    experimenter {
      orcid: "0000-0003-0344-3029"
      organization: "Department of Chemistry, Hunter College"
    }
    city: "New York"
    doi: "10.1039/D2FD00122E"
    publication_url: "https://doi.org/10.1039/D2FD00122E"
    record_created {
      time {
        value: "8/22/2024, 10:53 AM"
      }
      person {
        name: "Tzu-Hsuan Chao"
        orcid: "0000-0002-1345-0938"
        organization: "TAMU"
        email: "peterchao1@tamu.edu"
      }
    }
  }
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Photo Mechanochemical"
  }
  inputs {
    key: "acenaphthylene"
    value {
      components {
        identifiers {
          type: SMILES
          value: "C12=CC=CC(C=C3)=C1C3=CC=C2"
        }
        amount {
          moles {
            value: 7.89
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
        is_limiting: true
      }
      addition_order: 1
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 47.0
        }
      }
    }
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 53.0
        }
      }
    }
  }
  provenance {
    experimenter {
      orcid: "0000-0003-0344-3029"
      organization: "Department of Chemistry, Hunter College"
    }
    city: "New York"
    doi: "10.1039/D2FD00122E"
    publication_url: "https://doi.org/10.1039/D2FD00122E"
    record_created {
      time {
        value: "8/22/2024, 10:53 AM"
      }
      person {
        name: "Tzu-Hsuan Chao"
        orcid: "0000-0002-1345-0938"
        organization: "TAMU"
        email: "peterchao1@tamu.edu"
      }
    }
  }
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Photo Mechanochemical"
  }
  inputs {
    key: "acenaphthylene"
    value {
      components {
        identifiers {
          type: SMILES
          value: "C12=CC=CC(C=C3)=C1C3=CC=C2"
        }
        amount {
          moles {
            value: 7.89
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
        is_limiting: true
      }
      addition_order: 1
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 24.0
        }
      }
    }
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 76.0
        }
      }
    }
  }
  provenance {
    experimenter {
      orcid: "0000-0003-0344-3029"
      organization: "Department of Chemistry, Hunter College"
    }
    city: "New York"
    doi: "10.1039/D2FD00122E"
    publication_url: "https://doi.org/10.1039/D2FD00122E"
    record_created {
      time {
        value: "8/22/2024, 10:53 AM"
      }
      person {
        name: "Tzu-Hsuan Chao"
        orcid: "0000-0002-1345-0938"
        organization: "TAMU"
        email: "peterchao1@tamu.edu"
      }
    }
  }
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Photo Mechanochemical"
  }
  inputs {
    key: "acenaphthylene"
    value {
      components {
        identifiers {
          type: SMILES
          value: "C12=CC=CC(C=C3)=C1C3=CC=C2"
        }
        amount {
          moles {
            value: 7.89
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
        is_limiting: true
      }
      addition_order: 1
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 23.0
        }
      }
    }
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 77.0
        }
      }
    }
  }
  provenance {
    experimenter {
      orcid: "0000-0003-0344-3029"
      organization: "Department of Chemistry, Hunter College"
    }
    city: "New York"
    doi: "10.1039/D2FD00122E"
    publication_url: "https://doi.org/10.1039/D2FD00122E"
    record_created {
      time {
        value: "8/22/2024, 10:53 AM"
      }
      person {
        name: "Tzu-Hsuan Chao"
        orcid: "0000-0002-1345-0938"
        organization: "TAMU"
        email: "peterchao1@tamu.edu"
      }
    }
  }
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Photo Mechanochemical"
  }
  inputs {
    key: "acenaphthylene"
    value {
      components {
        identifiers {
          type: SMILES
          value: "C12=CC=CC(C=C3)=C1C3=CC=C2"
        }
        amount {
          moles {
            value: 7.89
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
        is_limiting: true
      }
      addition_order: 1
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 43.0
        }
      }
    }
    products {
      identifiers {
        type: SMILES
        value: "C12=CC=CC(C3C4C(C3C5=CC=C6)C7=C5C6=CC=C7)=C1C4=CC=C2"
      }
      measurements {
        type: YIELD
        percentage {
          value: 57.0
        }
      }
    }
  }
  provenance {
    experimenter {
      orcid: "0000-0003-0344-3029"
      organization: "Department of Chemistry, Hunter College"
    }
    city: "New York"
    doi: "10.1039/D2FD00122E"
    publication_url: "https://doi.org/10.1039/D2FD00122E"
    record_created {
      time {
        value: "8/22/2024, 10:53 AM"
      }
      person {
        name: "Tzu-Hsuan Chao"
        orcid: "0000-0002-1345-0938"
        organization: "TAMU"
        email: "peterchao1@tamu.edu"
      }
    }
  }
}
