name: "base_template"
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "PDI synthesis"
  }
  inputs {
    key: "inputs-111ad8"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=C(O1)C2=C3C(C1=O)=CC=CC3=CC=C2.[Na+]"
        }
        amount {
          moles {
            value: 25.0
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
        is_limiting: true
        crystal_parameters {
          type: ORTHROMBIC
          database_identifier {
            type: CSD
            value: "aaaaaaaa"
          }
        }
      }
      components {
        identifiers {
          type: SMILES
          value: "NC1=CC=C(OCC)C=C1"
        }
        amount {
          moles {
            value: 25.0
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    temperature {
      measurements {
        type: THERMOCOUPLE_INTERNAL
        temperature {
          value: 60.0
          units: CELSIUS
        }
      }
    }
    mechanochemistry {
      type: TWIN_SCREW
    }
  }
  observations {
    comment: "murky"
  }
  workups {
    type: FILTRATION
    input {
      components {
        identifiers {
          type: NAME
          value: "ethyl acetate"
        }
      }
    }
  }
  outcomes {
    conversion {
      value: 100.0
    }
    products {
      identifiers {
        type: SMILES
        value: "O=C1N(C2=CC=C(OCC)C=C2)C(C3=CC=CC4=CC=CC1=C34)=O"
      }
      measurements {
        type: YIELD
        percentage {
          value: 0.0
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      name: "Professor Professorson"
      orcid: "0000-0000-0000-0000"
      organization: "School of Chemistry and Chemical Engineering Fakesville"
    }
    city: "Fakeland"
    doi: "10.1002/000000"
    publication_url: "https://doi.org/1111/111111"
    record_created {
      time {
        value: "2025-09-24 12:51:00"
      }
      person {
        name: "Fake User"
        email: "user@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-d65777e162204aab9919dc51841e0001"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "PDI synthesis"
  }
  inputs {
    key: "inputs-111ad8"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=C(O1)C2=C3C(C1=O)=CC=CC3=CC=C2.[Na+]"
        }
        amount {
          moles {
            value: 25.0
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
        is_limiting: true
        crystal_parameters {
          type: ORTHROMBIC
          database_identifier {
            type: CSD
            value: "aaaaaaaa"
          }
        }
      }
      components {
        identifiers {
          type: SMILES
          value: "NC1=CC=C(OCC)C=C1"
        }
        amount {
          moles {
            value: 25.0
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    temperature {
      measurements {
        type: THERMOCOUPLE_INTERNAL
        temperature {
          value: 90.0
          units: CELSIUS
        }
      }
    }
    mechanochemistry {
      type: TWIN_SCREW
    }
  }
  outcomes {
    conversion {
      value: 100.0
    }
    products {
      identifiers {
        type: SMILES
        value: "O=C1N(C2=CC=C(OCC)C=C2)C(C3=CC=CC4=CC=CC1=C34)=O"
      }
      measurements {
        type: YIELD
        percentage {
          value: 0.0
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      name: "Professor Professorson"
      orcid: "0000-0000-0000-0000"
      organization: "School of Chemistry and Chemical Engineering Fakesville"
    }
    city: "Fakeland"
    doi: "10.1002/000000"
    publication_url: "https://doi.org/1111/111111"
    record_created {
      time {
        value: "2025-09-24 12:51:00"
      }
      person {
        name: "Fake User"
        email: "user@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-d65777e162204aab9919dc51841e0002"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "PDI synthesis"
  }
  inputs {
    key: "inputs-111ad8"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=C(O1)C2=C3C(C1=O)=CC=CC3=CC=C2.[Na+]"
        }
        amount {
          moles {
            value: 25.0
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
        is_limiting: true
        crystal_parameters {
          type: ORTHROMBIC
          database_identifier {
            type: CSD
            value: "aaaaaaaa"
          }
        }
      }
      components {
        identifiers {
          type: SMILES
          value: "NC1=CC=C(OCC)C=C1"
        }
        amount {
          moles {
            value: 25.0
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    temperature {
      measurements {
        type: THERMOCOUPLE_INTERNAL
        temperature {
          value: 110.0
          units: CELSIUS
        }
      }
    }
    mechanochemistry {
      type: TWIN_SCREW
      details: "in text, they say this was done in a tungsten carbide cell, in table it is specified as stainless steel"
    }
  }
  outcomes {
    conversion {
      value: 100.0
    }
    products {
      identifiers {
        type: SMILES
        value: "O=C1N(C2=CC=C(OCC)C=C2)C(C3=CC=CC4=CC=CC1=C34)=O"
      }
      measurements {
        type: YIELD
        percentage {
          value: 99.0
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      name: "Professor Professorson"
      orcid: "0000-0000-0000-0000"
      organization: "School of Chemistry and Chemical Engineering Fakesville"
    }
    city: "Fakeland"
    doi: "10.1002/000000"
    publication_url: "https://doi.org/1111/111111"
    record_created {
      time {
        value: "2025-09-24 12:51:00"
      }
      person {
        name: "Fake User"
        email: "user@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-d65777e162204aab9919dc51841e0003"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "PDI synthesis"
  }
  inputs {
    key: "inputs-111ad8"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=C(O1)C2=C3C(C1=O)=CC=CC3=CC=C2.[Na+]"
        }
        amount {
          moles {
            value: 25.0
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
        is_limiting: true
        crystal_parameters {
          type: ORTHROMBIC
          database_identifier {
            type: CSD
            value: "aaaaaaaa"
          }
        }
      }
      components {
        identifiers {
          type: SMILES
          value: "CCOC1=CC=C(C=C1)CN"
        }
        amount {
          moles {
            value: 25.0
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    temperature {
      measurements {
        type: THERMOCOUPLE_INTERNAL
        temperature {
          value: 110.0
          units: CELSIUS
        }
      }
    }
    mechanochemistry {
      type: TWIN_SCREW
    }
  }
  outcomes {
    conversion {
      value: 100.0
    }
    products {
      identifiers {
        type: SMILES
        value: "O=C1N(CC2=CC=C(OC)C=C2)C(C3=CC=CC4=CC=CC1=C34)=O"
      }
      measurements {
        type: YIELD
        percentage {
          value: 0.0
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      name: "Professor Professorson"
      orcid: "0000-0000-0000-0000"
      organization: "School of Chemistry and Chemical Engineering Fakesville"
    }
    city: "Fakeland"
    doi: "10.1002/000000"
    publication_url: "https://doi.org/1111/111111"
    record_created {
      time {
        value: "2025-09-24 12:51:00"
      }
      person {
        name: "Fake User"
        email: "user@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-d65777e162204aab9919dc51841e0004"
}
dataset_id: "cmcc_dataset-d65777e162204aab9919dc51841eaddb"
