name: "halogenation_10.1039.C3GC42104J"
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Li+].[Br-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: BALL_MILL
      frequency {
        value: 30.0
        units: HERTZ
      }
      duration {
        value: 0.5
        units: SECOND
      }
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Br-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 95.0
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00001"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Na+].[Br-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: BALL_MILL
      frequency {
        value: 30.0
        units: HERTZ
      }
      duration {
        value: 0.5
        units: SECOND
      }
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Br-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 99.0
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00002"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[K+].[Br-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: BALL_MILL
      frequency {
        value: 30.0
        units: HERTZ
      }
      duration {
        value: 0.5
        units: SECOND
      }
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Br-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 98.0
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00003"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Rb+].[Br-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: BALL_MILL
      frequency {
        value: 30.0
        units: HERTZ
      }
      duration {
        value: 0.5
        units: SECOND
      }
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Br-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 99.0
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00004"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Cs+].[Br-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: BALL_MILL
      frequency {
        value: 30.0
        units: HERTZ
      }
      duration {
        value: 0.5
        units: SECOND
      }
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Br-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 99.0
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00005"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Cu+].[Br-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: BALL_MILL
      frequency {
        value: 30.0
        units: HERTZ
      }
      duration {
        value: 0.5
        units: SECOND
      }
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Br-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 82.0
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00006"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Cu+2].[Br-].[Br-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: BALL_MILL
      frequency {
        value: 30.0
        units: HERTZ
      }
      duration {
        value: 0.5
        units: SECOND
      }
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Br-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 84.0
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00007"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "CC[NH+](CC)CC[Br-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: BALL_MILL
      frequency {
        value: 30.0
        units: HERTZ
      }
      duration {
        value: 0.5
        units: SECOND
      }
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Br-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 99.0
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00008"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "O=C(N1Br)CCC1=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: BALL_MILL
      frequency {
        value: 30.0
        units: HERTZ
      }
      duration {
        value: 0.5
        units: SECOND
      }
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Br-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 99.0
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00009"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Na+].[Br-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: HAND_GRIND
      duration {
        value: 4.0
        units: SECOND
      }
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Br-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 99.0
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00010"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Na+].[Br-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Br-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 0.0
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00011"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Na+].[Br-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Br-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 0.0
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00012"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Li+].[Br-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: BALL_MILL
      frequency {
        value: 30.0
        units: HERTZ
      }
      duration {
        value: 0.5
        units: SECOND
      }
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Br-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 82.0
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00013"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Li+].[Br-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: BALL_MILL
      frequency {
        value: 30.0
        units: HERTZ
      }
      duration {
        value: 0.5
        units: SECOND
      }
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Br-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 80.0
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00014"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Li+].[Br-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: HAND_GRIND
      liquid_assisted: true
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Br-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 94.0
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00015"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Na+].[Br-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: BALL_MILL
      frequency {
        value: 30.0
        units: HERTZ
      }
      duration {
        value: 0.5
        units: SECOND
      }
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Br-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 99.0
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00016"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Na+].[Br-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: BALL_MILL
      frequency {
        value: 30.0
        units: HERTZ
      }
      duration {
        value: 0.5
        units: SECOND
      }
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Br-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 99.0
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00017"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Na+].[Br-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: HAND_GRIND
      liquid_assisted: true
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Br-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 92.0
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00018"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Na+].[Cl-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: BALL_MILL
      frequency {
        value: 30.0
        units: HERTZ
      }
      duration {
        value: 0.5
        units: SECOND
      }
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Cl-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 9.2
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00019"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Cu+].[Cl-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: BALL_MILL
      frequency {
        value: 30.0
        units: HERTZ
      }
      duration {
        value: 0.5
        units: SECOND
      }
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Cl-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 3.6
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00020"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Cu+2].[Cl-].[Cl-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: BALL_MILL
      frequency {
        value: 30.0
        units: HERTZ
      }
      duration {
        value: 0.5
        units: SECOND
      }
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Cl-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 14.1
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00021"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "Cl[Cu-2](Cl)([OH2+])[OH2+]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: BALL_MILL
      frequency {
        value: 30.0
        units: HERTZ
      }
      duration {
        value: 0.5
        units: SECOND
      }
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Cl-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 74.25
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00022"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Cu+2].[Cl-].[Cl-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: HAND_GRIND
      liquid_assisted: true
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Br-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 69.3
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00023"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Na+].[Br-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: BALL_MILL
      frequency {
        value: 30.0
        units: HERTZ
      }
      duration {
        value: 0.5
        units: SECOND
      }
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Br-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 88.11
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00024"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Na+].[Br-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: HAND_GRIND
      liquid_assisted: true
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Br-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 71.28
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00025"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Cu+].[Br-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: BALL_MILL
      frequency {
        value: 30.0
        units: HERTZ
      }
      duration {
        value: 0.5
        units: SECOND
      }
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Br-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 41.0
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00026"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Cu+].[Br-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: HAND_GRIND
      liquid_assisted: true
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Br-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 52.47
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00027"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Cu+2].[Br-].[Br-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: BALL_MILL
      frequency {
        value: 30.0
        units: HERTZ
      }
      duration {
        value: 0.5
        units: SECOND
      }
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Br-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 32.8
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00028"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Cu+2].[Br-].[Br-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: HAND_GRIND
      liquid_assisted: true
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Br-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 53.35
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00029"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Na+].[I-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: BALL_MILL
      frequency {
        value: 30.0
        units: HERTZ
      }
      duration {
        value: 0.5
        units: SECOND
      }
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[I-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 49.0
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00030"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Na+].[I-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: HAND_GRIND
      liquid_assisted: true
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[I-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 46.06
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00031"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Cu+].[I-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: BALL_MILL
      frequency {
        value: 30.0
        units: HERTZ
      }
      duration {
        value: 0.5
        units: SECOND
      }
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[I-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 20.74
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00032"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Na+].[Cl-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: BALL_MILL
      frequency {
        value: 30.0
        units: HERTZ
      }
      duration {
        value: 0.5
        units: SECOND
      }
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Cl-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 11.75
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00033"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Cu+].[Cl-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: BALL_MILL
      frequency {
        value: 30.0
        units: HERTZ
      }
      duration {
        value: 0.5
        units: SECOND
      }
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Cl-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 0.0
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00034"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Cu+2].[Cl-].[Cl-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: BALL_MILL
      frequency {
        value: 30.0
        units: HERTZ
      }
      duration {
        value: 0.5
        units: SECOND
      }
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Cl-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 43.12
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00035"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Cu+2].[Cl-].[Cl-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: BALL_MILL
      frequency {
        value: 30.0
        units: HERTZ
      }
      duration {
        value: 0.5
        units: SECOND
      }
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Cl-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 20.46
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00036"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Cu+2].[Cl-].[Cl-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: HAND_GRIND
      liquid_assisted: true
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Cl-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 18.56
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00037"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Cu+].[Br-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: BALL_MILL
      frequency {
        value: 30.0
        units: HERTZ
      }
      duration {
        value: 0.5
        units: SECOND
      }
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Br-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 44.0
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00038"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Cu+].[Br-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: HAND_GRIND
      liquid_assisted: true
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Br-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 41.8
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00039"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Cu+].[Br-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: BALL_MILL
      frequency {
        value: 30.0
        units: HERTZ
      }
      duration {
        value: 0.5
        units: SECOND
      }
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Br-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 51.3
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00040"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Cu+].[Br-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: HAND_GRIND
      liquid_assisted: true
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Br-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 47.3
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00041"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Cu+2].[Br-].[Br-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: BALL_MILL
      frequency {
        value: 30.0
        units: HERTZ
      }
      duration {
        value: 0.5
        units: SECOND
      }
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Br-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 17.6
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00042"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Cu+2].[Br-].[Br-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: HAND_GRIND
      liquid_assisted: true
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[Br-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 45.76
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00043"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Na+].[I-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: BALL_MILL
      frequency {
        value: 30.0
        units: HERTZ
      }
      duration {
        value: 0.5
        units: SECOND
      }
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[I-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 71.78
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00044"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Na+].[I-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: HAND_GRIND
      liquid_assisted: true
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[I-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 58.5
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00045"
}
reactions {
  identifiers {
    type: REACTION_TYPE
    value: "Halogenation"
  }
  inputs {
    key: "inputs-5d6f2a"
    value {
      components {
        identifiers {
          type: SMILES
          value: "O=[C][Re]([C]=O)([C]=O)C1=CC=CC1"
        }
        amount {
          moles {
            value: 0.298
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[Cu+].[I-]"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
      components {
        identifiers {
          type: SMILES
          value: "[O-][O+]=O"
        }
        amount {
          moles {
            value: 0.596
            units: MILLIMOLE
          }
        }
        reaction_role: REACTANT
      }
    }
  }
  conditions {
    mechanochemistry {
      type: BALL_MILL
      frequency {
        value: 30.0
        units: HERTZ
      }
      duration {
        value: 0.5
        units: SECOND
      }
    }
  }
  outcomes {
    products {
      identifiers {
        type: SMILES
        value: "[Re]C1=CC=CC1.[I-]"
      }
      measurements {
        type: YIELD
        percentage {
          value: 0.0
        }
      }
      reaction_role: PRODUCT
    }
  }
  provenance {
    experimenter {
      organization: "Department of Chemistry and FRQNT Center for Green Chemistry and Catalysis, McGill University"
    }
    doi: "10.1039/C3GC42104J"
    publication_url: "https://pubs.rsc.org/en/content/articlelanding/2014/gc/c3gc42104j"
    record_created {
      time {
        value: "2025-05-11 22:13:47.176993"
      }
      person {
        name: "Mark Boyer"
        email: "maboyer@tamu.edu"
      }
    }
  }
  reaction_id: "cmcc-e3b4e61663914fdda67451e2f0a00046"
}
dataset_id: "cmcc_dataset-e3b4e61663914fdda67451e2f0a0093e"
